# -*- coding: utf-8 -*-
"""feature 분석 corr

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uFYz4lP49NUKrkkyRmniXGLn_hbsyDPD
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np

weather=pd.read_csv('weather_2020010100_2020123123.csv',encoding='cp949')

print(weather.info())

weather.isnull()

weather.drop(columns=['지점','지점명','일시','운형(운형약어)','현상번호(국내식)','기온 QC플래그','풍속 QC플래그','강수량 QC플래그','습도 QC플래그','현지기압 QC플래그','해면기압 QC플래그',
                      '일조 QC플래그','일사 QC플래그','지면온도 QC플래그','지면상태(지면상태코드)'],inplace=True)
#  1

weather['강수량(mm)'].fillna(0,inplace=True)

weather['풍속(m/s)'].fillna(0,inplace=True)

weather['습도(%)'].fillna(0,inplace=True)

weather['증기압(hPa)'].fillna(0,inplace=True)

# 2
weather['이슬점온도(°C)'].fillna(0,inplace=True)
weather['현지기압(hPa)'].fillna(0,inplace=True)

weather['일조(hr)'].fillna(0,inplace=True)
weather['해면기압(hPa)'].fillna(0,inplace=True)


# 3
weather['적설(cm)'].fillna(0,inplace=True)
weather['3시간신적설(cm)'].fillna(0,inplace=True)
weather['전운량(10분위)'].fillna(0,inplace=True)
weather['중하층운량(10분위)'].fillna(0,inplace=True)


# 4
weather['최저운고(100m )'].fillna(0,inplace=True)
weather['시정(10m)'].fillna(0,inplace=True)

weather['지면온도(°C)'].fillna(0,inplace=True)

weather['5cm 지중온도(°C)'].fillna(0,inplace=True)


# 5
weather['10cm 지중온도(°C)'].fillna(0,inplace=True)
weather['20cm 지중온도(°C)'].fillna(0,inplace=True)

weather['30cm 지중온도(°C)'].fillna(0,inplace=True)

weather['일사(MJ/m2)'].fillna(0,inplace=True)

weather['기온(°C)'].fillna(0,inplace=True)

weather.dropna(how='any',axis=1,inplace=True)
#print(weather)

from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()
result=scaler.fit_transform(weather.iloc[:,1:])
df_scld= pd.DataFrame(data=result,index=weather.index,columns=weather.columns[1:])
#print(df_scld)

gen = pd.read_csv('gen_20201231.csv',encoding='cp949')

gen.drop(columns=['연료원','지역세부구분'],inplace=True)

last_month_2020 = gen[gen['거래일']=='2020-12-31']
last_day_2020 = last_month_2020[last_month_2020['시간']==23]
Time = gen.iloc[:8760,:2]
Power = gen.iloc[:8760,2]

sum_data = pd.concat([Time,df_scld,Power],axis=1)
print(sum_data.head(24))

# 상관계수 히트맵 

import seaborn as sns
import matplotlib.pyplot as plt

sum_data.corr()